### ISSUE TITLE
【CSS】background-clip

### ISSUE THREAD

**Issue by S-A-V** [S-A-V/weekly-notes#1]
# background-clip

## 文档

<https://developer.mozilla.org/zh-CN/docs/Web/CSS/background-clip>

### HTML

```html
<div class="demo border">background-clip</div>
<div class="demo text">background-clip</div>
```

### CSS

```css
.demo {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 240px;
  height: 120px;
  border-radius: 4px;
  border-width: 4px;
  border-style: solid;
}

.border {
  border-color: transparent;
  background:
    linear-gradient(90deg, #003755, #597581, #969094, #b1a477) padding-box,
    linear-gradient(90deg, #006484, #5aacc4, #8e888a, #e9d18b) border-box;
  color: #fff;
}

.text {
  border-color: #006484;
  background-image: linear-gradient(90deg, #003755, #597581, #969094, #b1a477);
  background-clip: text;
  color: transparent;
}
```

### 结果

![600*360](https://github.com/user-attachments/assets/5afba151-5f59-487e-9ba0-0fefc1bff5b3)
