### ISSUE TITLE
【CSS】aspect-ratio

### ISSUE THREAD

**Issue by S-A-V** [S-A-V/weekly-notes#2]
# aspect-ratio

通过 `aspect-ratio` 属性来设置元素的宽高比。

## 文档

<https://developer.mozilla.org/zh-CN/docs/Web/CSS/aspect-ratio>

## 语法

```css
aspect-ratio: <width> / <height>;
```

### HTML

```html
<div class="card card-1-1">1:1</div>
<div class="card card-16-9">16:9</div>
```

### CSS

```css
.card {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 90px;
}

.card-1-1 {
  aspect-ratio: 1 / 1;
}

.card-16-9 {
  aspect-ratio: 16 / 9;
}
```

### 结果

![400*240](https://github.com/user-attachments/assets/dc7251fc-ac76-4fa0-8384-e9cd1b58316d)
